// Copy Real private store helpers for Cloudflare Pages Functions.
// Never expose STORE_PRODUCTS_JSON, Stripe keys, or R2 object keys to the client.
export const json=(value,status=200,headers={})=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff",...headers}});
export const noCache={"cache-control":"no-store","x-content-type-options":"nosniff"};
export function requireServices(env,keys) {const absent=keys.filter(k=>!env[k]);if(absent.length) throw new Error("Store configuration missing: "+absent.join(", "));}
export function enabledStore(env){return env.STORE_ENABLED==="true" && env.STORE_MODE==="test" && env.STRIPE_SECRET_KEY?.startsWith("sk_test_");}
export function allowedOrigin(request,env){const origin=request.headers.get("origin");if(!origin)return false;const self=new URL(request.url).origin;return origin===self && (!env.STORE_PUBLIC_ORIGIN || origin===env.STORE_PUBLIC_ORIGIN);}
export function products(env){let parsed;try{parsed=JSON.parse(env.STORE_PRODUCTS_JSON||"{}");}catch{throw new Error("Invalid private product configuration");}return parsed;}
export function lookupProduct(env,sku){const product=products(env)[sku];if(!product||!product.enabled||!product.r2Key||!Number.isSafeInteger(product.amount)||product.amount<100||!["thb","gbp"].includes(product.currency))return null;return product;}
export function baseOrigin(req,env){const actual=new URL(req.url).origin;return env.STORE_PUBLIC_ORIGIN===actual?actual:actual;}
export async function stripe(env,path,init={}){const response=await fetch("https://api.stripe.com/v1/"+path,{...init,headers:{"authorization":"Bearer "+env.STRIPE_SECRET_KEY,...(init.headers||{})}});const value=await response.json();if(!response.ok)throw new Error("Stripe API: "+(value.error?.type||"request_failed"));return value;}
export async function sha256(text){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");}
export function randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return [...bytes].map(b=>b.toString(16).padStart(2,"0")).join("");}
export async function verifyStripeSignature(body,header,secret){if(!header||!secret)return false;const fragments=Object.fromEntries(header.split(",").map(p=>p.split("=",2)));const timestamp=Number(fragments.t);if(!Number.isFinite(timestamp)||Math.abs(Date.now()/1000-timestamp)>300||!fragments.v1)return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const mac=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(fragments.t+"."+body)));const sig=[...mac].map(b=>b.toString(16).padStart(2,"0")).join("");if(sig.length!==fragments.v1.length)return false;let diff=0;for(let i=0;i<sig.length;i++)diff|=sig.charCodeAt(i)^fragments.v1.charCodeAt(i);return diff===0;}
export async function markPaid(env,session){if(session.payment_status!=="paid"||!session.id||!session.client_reference_id)return false;const order=await env.STORE_DB.prepare("SELECT id,sku,amount,currency,session_id,status FROM store_orders WHERE id=?").bind(session.client_reference_id).first();if(!order||order.session_id!==session.id||order.status==="cancelled")return false;const configured=lookupProduct(env,order.sku);if(!configured||configured.amount!==order.amount||configured.currency!==order.currency||session.amount_total!==order.amount||session.currency!==order.currency)return false;await env.STORE_DB.prepare("UPDATE store_orders SET status='paid',paid_at=? WHERE id=? AND status='pending'").bind(Date.now(),order.id).run();return true;}
export function err(e){console.error("Copy Real store:",e?.message||e);return json({error:"Store temporarily unavailable"},503);}
